#!/bin/bash
#PBS -N Dori
#PBS -M hyschive@gmail.com
#PBS -m abe
#PBS -k oe
#PBS -q workq
#PBS -l walltime=720:00:00
#PBS -l nodes=1:ppn=6

cd $PBS_O_WORKDIR

## OpenMPI 1.8.1
## ------------------------
##for NRank (NGPU) > 1
##mpirun -map-by ppr:2:socket:pe=3 ./Swim 1>>stdout 2>>stderr

##for NRank (NGPU) = 1
##mpirun -map-by ppr:1:socket:pe=3 ./Swim 1>>stdout 2>>stderr


## OpenMPI 1.4.3
## ------------------------
mpirun -np 2 --bind-to-socket ./Swim 1>>stdout 2>>stderr
